# permissions for end users to view interactivejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: interactivejob-viewer-role
rules:
- apiGroups:
  - batch.k8.interactive.job
  resources:
  - interactivejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.k8.interactive.job
  resources:
  - interactivejobs/status
  verbs:
  - get
