---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.k8.interactive.job
  resources:
  - interactivejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8.interactive.job
  resources:
  - interactivejobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.k8.interactive.job
  resources:
  - interactivejobs/status
  verbs:
  - get
  - patch
  - update
