apiVersion: batch.k8.interactive.job/v1
kind: InteractiveJob
metadata:
  name: interactivejob-sample
spec:
  jobtemplate:
    spec: 
      template: 
        metadata:
          labels:
            app: jupyter
        spec:
          activeDeadlineSeconds: 60
          restartPolicy: Never
          containers:
          - name: minimal-notebook
            image: jupyter/tensorflow-notebook:latest
            ports:
            - containerPort: 8888

