kind: Job
apiVersion: batch/v1
metadata:
  name: jupyter
spec:
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      restartPolicy: Never
      containers:
      - name: minimal-notebook
        image: jupyter/tensorflow-notebook:latest
        ports:
        - containerPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: jupyter-service
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
  - port: 8888
