apiVersion: batch.k8.interactive.job/v1
kind: InteractiveJob
metadata:
  name: jupyter-ij
  labels:
    app: jupyter-ij
spec:
  service:
    ports: 
    - 8888
  jobtemplate:
    activeDeadlineSeconds: 6000
    backoffLimit: 1
    template: 
      metadata:
        labels:
          app: jupyter-ij
      spec:
        restartPolicy: Never
        containers:
        - name: minimal-notebook
          image: jupyter/tensorflow-notebook:latest
          ports:
          - containerPort: 8888

